### ISSUE TITLE
How can I set custom editor on columns after paste?

### ISSUE THREAD

**Issue by jackielii** [Celebio/SlickGrid#1]
Hi,

I have fields that I want to use say date editor, when copy and paste, I need to change the editor to this "FormulaEditor" right? and can I hook up to onPaste to change the column editor back to date editor?

Thanks very much,
Jackie

**Comment by Celebio** [comment]
No you use DateEditor directly, I let FormulaEditor example because the test html is a copy of another one.
I removed the FormulaEditor of the example in the last commit and I put some other custom editors.
Now we also have the support of serializing/unserializing values from custom editors.
