### ISSUE TITLE
Copy/Paste does not work inside bootstrap modal

### ISSUE THREAD

**Issue by Cfuzz** [Celebio/SlickGrid#14]
The problem seems to be related to focus stealing of items focused outside the modal. I successfully got it to work by creating the textarea inside the targetted element (e.target) instead of document.body in the 'handleKeyDown' function.

**Comment by Celebio** [comment]
Good finding. Could you provide a pull request ? (please be sure that the behavior is not broken in the classical testcase (outside bootstraps modal) and works fine with ie7+)

**Comment by Celebio** [comment]
Commit from pull request: 27719ba6e4fd24c37d14bd65d3cd6bd30bdc2e7d should fix this.
