### ISSUE TITLE
copy to multiple cells

### ISSUE THREAD

**Issue by YoSev** [Celebio/SlickGrid#3]
Hello,

i would like to copy ONE cell to multiple cells.
Like a:1  to a:2-a:8

any ideas?

**Comment by Celebio** [comment]
Ok, I'm about to code it.

**Comment by Celebio** [comment]
Check the last commit. Do CTRL+C on A1, select A2:A8, CTRL+V

**Comment by YoSev** [comment]
Can you update the master branch so i can use the example page to test it?

**Comment by YoSev** [comment]
Thanks for the quick (free) work btw!

**Comment by Celebio** [comment]
You're welcome :-)

You can checkout this commit : https://github.com/Celebio/SlickGrid/commit/5c511d6c0faff4d78464914cf975f6ede06e40ee

or test it online :
http://labs.nereo.fr/SlickGrid/examples/example-excel-compatible-spreadsheet.html

**Comment by YoSev** [comment]
Works like a charm :-)

**Comment by YoSev** [comment]
After using this new feature, i came across a problem regarding the Longtext editor.
It seems like the cells handled by the Longtext editor are not copyable (errors)

**Comment by Celebio** [comment]
I don't understand, could you please provide a testcase (ideally online example) ?

**Comment by YoSev** [comment]
Sure:
http://qill.event7.net/sheet/sheet.php
The Description cells cannot be copied.. they are handled by the Longtext editor.

**Comment by Celebio** [comment]
It seems to be a problem with recent SlickGrid (mine is quite old). I will deal with when merging with the mainstream version. For the moment, you can change those lines:

``` javascript
var editorArgs = {
        'container':$(document),  // a dummy container
        'column':columnDef
      };
```

to

``` javascript
var editorArgs = {
        'container':$(document),  // a dummy container
        'column':columnDef,
        'position':{'top':0, 'left':0}
      };
```

in slick.cellcopymanager.js. Be careful there are twice.
I didn't test, could you give me a feedback?

**Comment by YoSev** [comment]
Ah, perfect.
You need to add the position value to both arrays! 
Line 66 & Line 85

Thanks once again :-)
