### ISSUE TITLE
Undo/redo support

### ISSUE THREAD

**Issue by mplorentz** [Celebio/SlickGrid#7]
Right now the copy and paste actions are not really compatible with undo/redo features. 

Copy/paste actions would need to be packaged up into an object with execute() and undo() methods as in https://github.com/Celebio/SlickGrid/blob/master/examples/example3b-editing-with-undo.html

**Comment by mplorentz** [comment]
I'm going to have to implement this for my site, I will submit a pull request when I do and you can see how you like it.

**Comment by Celebio** [comment]
ok :)

**Comment by AbhinayGupta** [comment]
Any news on this, any timeline? We also need the functionality on our website.

**Comment by mplorentz** [comment]
I have the code written, I just need to merge it in. I'll get to it this week or next week.

**Comment by mplorentz** [comment]
Just submitted the pull request, see Issue #9.
